from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class Cell:
    value: Any
    description: str = "Generated by verbosa"
    dtype: Optional[type] = None